version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    ports:
      - "80:4000"

  populatedb:
    build: ./filldb/
    restart: "no"

  mongodb:
    image: mongo
    restart: always
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongodb"]
    ports:
      - "27017:27017"

  mongodb2:
    image: mongo
    restart: always
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongodb2"]
    ports:
      - "27018:27017"

  mongodb3:
    image: mongo
    restart: always
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongodb3"]
    ports:
      - "27019:27017"

  redis-cach:
#    build: .
    image: redis:alpine
    container_name: 'gcloud_app_redis'
    ports:
      - "6379:6379"
    restart: always

  frontend:
    build: ./frontend/
#    image: gcr.io/google-samples/microservices-demo/frontend:v0.5.1
    ports:
      - "8080"
    depends_on:
      - mongodb
    environment:
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - CART_SERVICE_ADDR=cartserv:7070
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
    restart: always
