version: "3"
services:
  frontend:
    build: ./frontend/
#    image: gcr.io/google-samples/microservices-demo/frontend:v0.5.1
    container_name: 'app_frontend'
    ports:
      - "80:8080"
    environment:
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - CART_SERVICE_ADDR=cartserv:7070
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
    restart: always

  redis-cach:
#    build: .
    image: redis:alpine
    container_name: 'gcloud_app_redis'
    ports:
      - "6379:6379"
    restart: always

